/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Adaptive Media Engine Named Tokens
        'parchment-canvas': '#fdf9f0',
        'parchment-surface': '#f2ede5',
        'parchment-border': '#cfcac0',
        'obsidian-canvas': '#121110',
        'obsidian-surface': '#1a1816',
        'obsidian-border': '#2e2a26',
        'gilded-amber': '#c4975a',
        'linen-white': '#faf8f5',

        // Dynamic System Palette (CSS Variables for dark/light reading room modes)
        background: 'var(--surface)',
        surface: 'var(--surface)',
        'surface-dim': 'var(--surface-dim)',
        'surface-bright': 'var(--surface-bright)',
        'surface-container-lowest': 'var(--surface-container-lowest)',
        'surface-container-low': 'var(--surface-container-low)',
        'surface-container': 'var(--surface-container)',
        'surface-container-high': 'var(--surface-container-high)',
        'surface-container-highest': 'var(--surface-container-highest)',
        'surface-variant': 'var(--surface-variant)',
        'on-surface': 'var(--on-surface)',
        'on-surface-variant': 'var(--on-surface-variant)',
        'inverse-surface': 'var(--inverse-surface)',
        'inverse-on-surface': 'var(--inverse-on-surface)',
        outline: 'var(--outline)',
        'outline-variant': 'var(--outline-variant)',
        primary: {
          DEFAULT: 'var(--primary)',
          container: 'var(--primary-container)',
          'on-container': 'var(--on-primary-container)',
        },
        'on-primary': 'var(--on-primary)',
        secondary: {
          DEFAULT: 'var(--secondary)',
          container: 'var(--secondary-container)',
          'on-container': 'var(--on-secondary-container)',
        },
        'on-secondary': 'var(--on-secondary)',
        tertiary: {
          DEFAULT: 'var(--tertiary)',
          container: 'var(--tertiary-container)',
          'on-container': 'var(--on-tertiary-container)',
        },
        'on-tertiary': 'var(--on-tertiary)',
        error: {
          DEFAULT: 'var(--error)',
          container: 'var(--error-container)',
          'on-container': 'var(--on-error-container)',
        },
        'on-error': 'var(--on-error)',
        border: 'var(--border)',
        card: {
          DEFAULT: 'var(--surface-container-low)',
          foreground: 'var(--on-surface)',
        },
        muted: {
          DEFAULT: 'var(--surface-container)',
          foreground: 'var(--on-surface-variant)',
        },
      },
      fontFamily: {
        serif: ['"EB Garamond"', 'Georgia', 'serif'],
        sans: ['"Karla"', 'system-ui', 'sans-serif'],
        mono: ['"Space Mono"', 'monospace'],
        headline: ['"EB Garamond"', 'Georgia', 'serif'],
        body: ['"Karla"', 'system-ui', 'sans-serif'],
        'display-hero': ['"EB Garamond"', 'Georgia', 'serif'],
        'headline-lg': ['"EB Garamond"', 'Georgia', 'serif'],
        'headline-md': ['"EB Garamond"', 'Georgia', 'serif'],
        'headline-sm': ['"EB Garamond"', 'Georgia', 'serif'],
        'body-lg': ['"Karla"', 'sans-serif'],
        'body-md': ['"Karla"', 'sans-serif'],
        'body-sm': ['"Karla"', 'sans-serif'],
        'meta-tag': ['"Space Mono"', 'monospace'],
        'meta-label': ['"Space Mono"', 'monospace'],
        'button-text': ['"Space Mono"', 'monospace'],
      },
      fontSize: {
        'display-hero': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'display-hero-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-lg': ['38px', { lineHeight: '48px', letterSpacing: '-0.015em', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '400' }],
        'headline-md': ['26px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'button-text': ['11px', { lineHeight: '16px', letterSpacing: '0.15em', fontWeight: '500' }],
        'meta-label': ['11px', { lineHeight: '16px', letterSpacing: '0.18em', fontWeight: '400' }],
        'meta-tag': ['10px', { lineHeight: '14px', letterSpacing: '0.12em', fontWeight: '500' }],
      },
      spacing: {
        'shelf-gap': '4.5rem',
        'shelf-gap-mobile': '2.5rem',
        'gutter-desktop': '2rem',
        'gutter-mobile': '1rem',
        'spine-gap': '2px',
        'pill-padding-x': '1.125rem',
        'pill-padding-y': '0.375rem',
        'margin-container': 'max(2rem, 5vw)',
      },
      borderRadius: {
        DEFAULT: '1rem',
        sm: '0.5rem',
        md: '1.5rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      boxShadow: {
        'shelf-ledge': '0 8px 18px -4px rgba(26, 24, 22, 0.14)',
        'tactile-case': '0 12px 24px -6px rgba(0, 0, 0, 0.28), 0 4px 8px -2px rgba(0, 0, 0, 0.16)',
        'tactile-hover': '0 24px 38px -8px rgba(0, 0, 0, 0.45), 0 8px 16px -4px rgba(0, 0, 0, 0.25)',
        'glass-modal': '0 24px 48px -12px rgba(26, 24, 22, 0.18)',
      },
      animation: {
        rise: 'rise 0.5s ease-out forwards',
        'shelve-in': 'shelve-in 0.6s cubic-bezier(0.16, 1, 0.32, 1) forwards',
      },
      keyframes: {
        rise: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'shelve-in': {
          '0%': { opacity: '0', transform: 'translateY(16px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
